services:
  - type: web
    name: tawasl-ai-video-analysis
    env: python
    buildCommand: |
      apt-get clean && \
      apt-get update && \
      apt-get install -y ffmpeg libgl1 libglib2.0-0 && \
      apt-get clean && \
      pip install -r server/ai-scripts/requirements.txt
    plan: free 
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
