services:
  - type: web
    name: tawasl-ai-video-analysis
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y ffmpeg libgl1 libglib2.0-0 && \
      pip install -r requirements.txt
    startCommand: python server/ai-scripts/ai_strict_video_analysis.py
    plan: free 
