services:
  - type: web
    name: tawasl-ai-video-analysis
    env: docker
    dockerfilePath: server/ai-scripts/Dockerfile
    plan: free 
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
