services:
  - type: web
    name: tawasl-ai-video-analysis
    env: python
    buildCommand: |
      pip install -r server/ai-scripts/requirements.txt
    plan: free 
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
